version: "3.9"
services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  server:
    depends_on:
      - postgresql
    image: weather-app-server
    container_name: weather-app-server
    build:
      context: ../server
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/*.jar
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456

  client:
    depends_on:
      - postgresql
      - server
    image: weather-app-client
    container_name: weather-app-client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"